version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: nginx-reverse-proxy
    depends_on:
        - ordina-solid-server
        
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/sites-available/css.conf
    ports:
      - 443:443
      - 80:80

  ordina-solid-server:
    image: solidproject/community-server:latest
    container_name: ordina-solid-server
    build:
      args: 
        - -b
        - https://www.ordinasolid.cloud
        - -t
        - -l
        - debug   
    ports:
      - 3000:3000
    restart: on-failure

